language: c

before_script: bash .travis-setup.sh

script: bash .travis.sh

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env :
        - OCAML_VERSION=4.07.0
    - os: linux
      dist: trusty
      sudo: required
      env :
        - OCAML_VERSION=4.08.0
      jdk :
        - openjdk11
    - os: osx
      jdk :
        - oraclejdk11

notifications:
  email : false

